### PR TITLE
Remove unused sandboxes.

### PR DESCRIPTION
**Pull request by richardbporter**
These URL's don't resolve to anything. Can they be removed?

jfinley-sandbox.lab.uiowa.edu
kflinn-sandbox.lab.uiowa.edu
kjohns14-sandbox.lab.uiowa.edu
lbaas-sandbox.lab.uiowa.edu

### CODE REVIEW

**Comment by genjohnson** [comment]
@richardbporter I'll check with the site owners if they are using these. 

I tend not to have Hostmaster create CNAMEs for the sandbox sites, so (for sandbox sites) that's not necessarily an indicator that the sites are not being used.

**Comment by genjohnson** [comment]
I've contacted the site owners and am waiting on responses.

**Comment by genjohnson** [comment]
jfinley, kflinn, and lbaas can be removed. Katie Johnson is out of the office until Monday, so still waiting on a response about kjohns14-sandbox.lab.uiowa.edu

**Comment by richardbporter** [comment]
Thanks. I'll use jfinley, kflinn, and lbaas to test deprovisioning command.

**Pull request closed without merging**
